columns:
  date_received: object
  product: object
  sub_product: object
  issue: object
  sub_issue: object
  consumer_complaint_narrative: object
  company_public_response: object
  company: object
  state: object
  zipcode: object
  tags: object
  consumer_consent_provided: object
  submitted_via: object
  date_sent_to_company: object
  company_response_to_consumer: object
  timely_response: object
  consumer_disputed?: object
  complaint_id: int64 

target_column: product




  



